### ISSUE TITLE
Hm... having issues with compiling

### ISSUE THREAD

**Issue by JasonGiedymin** [kripken/gmp.js#3]
OSX 10.8.2

I have emscripten and it works fine. I also used homebrew to install gmp and llvm. Manually built clang.

Emscripten tests work great.

I can manually configure and make gmp but it emcc fails. Here is the log. Before I start digging wondered if you knew what could be up?

checking build system type... none-none-none
checking host system type... none-none-none
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=long
checking compiler /usr/local/emscripten/emcc  ... no
checking ABI=longlong
checking compiler /usr/local/emscripten/emcc  ... no
checking for none-gcc... /usr/local/emscripten/emcc
checking whether the C compiler works... no
configure: error: in `/Users/jason/programming/sandbox/gmp.js':
configure: error: C compiler cannot create executables

**Comment by JasonGiedymin** [comment]
After some sleep I found that clang was not where it was expecting it to be.

**Comment by ted-strauss-K1** [comment]
Where was it expecting it to be?
I'm having the same issue. thx
